### ISSUE TITLE
No working for me

### ISSUE THREAD

**Issue by aloisioa** [mikesparr/Kraken_Example_i18n_Helper#1]
I use these dependencies: 
"makara": "^0.3.4",
"nconf": "^0.6.8",
"adaro": "^0.1.5",
"dustjs-helpers": "^1.2.0",
"dustjs-linkedin": "^2.3.6",
"engine-munger": "^0.2.0",
"express": "^4.3.0",
"kraken-devtools": "^1.0.0",
"kraken-js": "^1.0.1",
"localizr": "^0.1.0",
"node-sass": "^0.8.4"

There is no error, just nothing is displayed.

If I return chunk.write('button TEST button');
I have a button in my page, so the problem is the function, but where ? :)

**Comment by mikesparr** [comment]
Please follow the content in the README file.  This was provided based on personal use on an earlier version of KrakenJS so you may need to fork and adjust for your specific version. The version this was built for used the dependencies in the package.json file also included with this git repo.
- https://github.com/mikesparr/Kraken_Example_i18n_Helper/blob/master/package.json

If I upgrade to latest versions and update the code in my personal project, I'll share that with updates in this repo, but no promises. Also, if you decide to update to work for your project with later versions and want to contribute fix, fork this repo and issue pull request with your changes and I'll consider, again no promises. ;-)
